//  cart reducer actions
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const INCREMENT_PRODUCT_QUANTITY = "INCREMENT_PRODUCT_QUANTITY";
export const DECREMENT_PRODUCT_QUANTITY = "DECREMENT_PRODUCT_QUANTITY";
//  products reducer actions
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const ADD_DASHBOARD_PRODUCT = "ADD_DASHBOARD_PRODUCT";
export const UPDATE_DASHBOARD_PRODUCT = "UPDATE_DASHBOARD_PRODUCT";
export const DELETE_DASHBOARD_PRODUCT = "DELETE_DASHBOARD_PRODUCT";
//  categories reducer actions
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const DELETE_CATEGORIES = "DELETE_CATEGORIES";
